/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-18 05:17:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex08_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://pinnpublic.dothome.co.kr/cdn/example-min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	body {\r\n");
      out.write("		margin-bottom: 300px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <h1>컨트롤 입력 + 전송</h1>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 보통 다 GET말고 POST를 사용한다 -->\r\n");
      out.write("   <form method=\"POST\" action=\"ex08_ok.jsp\">\r\n");
      out.write("   <table class=\"vertical\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>텍스트 박스</th>\r\n");
      out.write("         <td><input type=\"text\" name=\"txt1\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>암호 박스</th>\r\n");
      out.write("         <td><input type=\"password\" name=\"txt2\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>다중 텍스트</th>\r\n");
      out.write("         <td><textarea name= \"txt3\"></textarea></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>체크 박스</th>\r\n");
      out.write("         <td><input type=\"checkbox\" name=\"cb1\" value=\"yes\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>체크 박스</th>\r\n");
      out.write("         <td>\r\n");
      out.write("         	<h3>취미를 선택하세요.</h3>\r\n");
      out.write("         	<label><input type=\"checkbox\" name=\"cb2\" value=\"독서\">독서</label>\r\n");
      out.write("         	<label><input type=\"checkbox\" name=\"cb3\" value=\"운동\">운동</label>\r\n");
      out.write("         	<label><input type=\"checkbox\" name=\"cb4\" value=\"코딩\">코딩</label>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>체크 박스</th>\r\n");
      out.write("         <td>\r\n");
      out.write("         	<h3>취미를 선택하세요.</h3>\r\n");
      out.write("         	<label><input type=\"checkbox\" name=\"cb5\" value=\"독서\">독서</label>\r\n");
      out.write("         	<label><input type=\"checkbox\" name=\"cb5\" value=\"운동\">운동</label>\r\n");
      out.write("         	<label><input type=\"checkbox\" name=\"cb5\" value=\"코딩\">코딩</label>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>라디오 버튼</th>\r\n");
      out.write("         <td>\r\n");
      out.write("         	<h3>성별을 선택하시오.</h3>\r\n");
      out.write("         	<label><input type=\"radio\" name=\"rb\" value=\"male\" checked>남자</label>         	\r\n");
      out.write("         	<label><input type=\"radio\" name=\"rb\" value=\"female\">여자</label>\r\n");
      out.write("         </td>      \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("			<th>셀렉트 박스</th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select name=\"sel1\">\r\n");
      out.write("					<option value=\"1\">사과</option>\r\n");
      out.write("					<option value=\"2\">바나나</option>\r\n");
      out.write("					<option value=\"3\">포도</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>셀렉트 박스</th>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select name=\"sel2\" multiple>\r\n");
      out.write("					<option value=\"1\">사과</option>\r\n");
      out.write("					<option value=\"2\">바나나</option>\r\n");
      out.write("					<option value=\"3\">포도</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>히든 태그</th>\r\n");
      out.write("			<td><input type=\"hidden\" name=\"txt4\" value=\"hong\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>날짜</th>\r\n");
      out.write("			<td><input type=\"date\" name=\"regdate\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>범위</th>\r\n");
      out.write("			<td><input type=\"range\" name=\"min\" min=\"10\" max=\"1000\" step=\"10\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>색상</th>\r\n");
      out.write("			<td><input type=\"color\" name=\"color\" style=\"height: 50px;\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   <div>\r\n");
      out.write("		<input type=\"submit\" value=\"보내기\">\r\n");
      out.write("		<input type=\"button\" value=\"클릭\" id=\"btn1\">\r\n");
      out.write("		<input type=\"button\" value=\"클릭\" id=\"btn2\">\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <input type=\"hidden\" name=\"count\">\r\n");
      out.write("   </form>\r\n");
      out.write("   \r\n");
      out.write("   	<h1>링크</h1>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"ex08_ok.jsp?id=hong&pw=1234\">링크입니다.</a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("   <script src=\"http://pinnpublic.dothome.co.kr/cdn/example-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("	   let count = 0;	//서버로 전송하고 싶다\r\n");
      out.write("		\r\n");
      out.write("		$('#btn1').click(function() {\r\n");
      out.write("			count++;\r\n");
      out.write("			$('input[name=count]').val(count);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#btn2').click(function() {\r\n");
      out.write("			location.href = 'ex08_ok.jsp?id=test&pw=1111';\r\n");
      out.write("		});\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
